# general settings
name: 15_WEI_train  # add debug for quick debug
model_type: WEI_train_model
num_gpu:  1 #4
manual_seed: 10

datasets:
  train:
    name: highrev-train
    type: HighREV_train_dataset

    dataroot: /opt/data/private/wsy/Datasets/HighREV

    moment_events: 9
    norm_voxel: false

    # augment
    lq_size:
      - 256
      - 256

    io_backend:
      type: disk

    # data loader settings
    use_shuffle: true
    num_worker_per_gpu: 8
    batch_size_per_gpu: 4
    dataset_enlarge_ratio: 4
    prefetch_mode: cuda
    pin_memory: true

  val:
    name: highrev-val
    type: HighREV_train_dataset
    dataroot: /opt/data/private/wsy/Datasets/HighREV/
    dataroot_voxel: /opt/data/private/wsy/Datasets/HighREV/

    moment_events: 9
    norm_voxel: false

    lq_size:
      - 256
      - 256

    io_backend:
      type: disk

dataset_name: HighREV

# network structures
network_g:
  type: FinalBidirectionAttenfusion_WEI
  img_chn: 3
  ev_chn: 2
  num_encoders: 3
  base_num_channels: 32
  num_block: 1
  num_residual_blocks: 2

# path
path:
  pretrain_network_g: ~
  strict_load_g: true
  resume_state: ~
  training_states: ~ # save current trainig model states, for resume

# training settings
train:
  optim_g:
    type: AdamW
    lr: !!float 2e-4
    weight_decay: !!float 1e-4
    betas: [0.9, 0.99]

  scheduler:
    type: CosineAnnealingRestartLR
    periods: [200000]
    restart_weights: [1]
    eta_min: !!float 1e-7

  total_iter: 200000
  warmup_iter: -1 # no warm up

  # losses
  pixel_opt:
    type: PSNRLoss
    loss_weight: 1
    reduction: mean

# validation settings
val:
  val_freq: !!float 2e4
  save_img: true
  save_gt: false
  cal_metrics: true 

# logging settings
logger:
  print_freq: !!float 1e2
  save_checkpoint_freq: !!float 5e4
  use_tb_logger: true

# dist training settings
dist_params:
  backend: nccl
  port: 29500
